server:
  port: 8083
spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: dfood-orders-service
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: ${DB_HOST:jdbc:postgresql://localhost:5432/orders_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
products-service:
  url: ${PRODUCTS_URL:http://localhost:8080/products}
customers-service:
  url: ${CUSTOMERS_URL:http://localhost:8082/customers}
service-bus:
  connection-string: ${SB_CONNECTION_STRING}
  queue-name: ${SB_QUEUE_NAME}